-- Auto-generated by .trellis. Do not edit.
import Tablet.CloseToDiagonalTheorem
import Tablet.LinearOffDiagonalTheorem
import Tablet.MainTheorem
import Tablet.MulticolorTheorem
import Tablet.OffDiagonalGeneralTheorem
import Tablet.Preamble
